[app]
name = "Hello Name Badge Smaller"
category = "Badge"
wifi_preference = false

[entry]
class = "NameBadge"

[metadata]
author = "JonSpriggs"
license = "Unlicense"
url = "https://github.com/jontheniceguy/tildagon-name-badge"
description = "A simple 'Hello my name is' sticker style Tildagon name badge"
version = "0.0.4"
